server:
  port: 8080
  servlet:
    contextPath: /module

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: Sample Module Application

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true